package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cab generated by hbm2java
 */
public class Cab  implements java.io.Serializable {


     private String cabId;
     private VehicleModel vehicleModel;
     private VehicleStatus vehicleStatus;
     private ServiceProvider serviceProvider;
     private VehicleColour vehicleColour;
     private Double costPerKm;
     private Set serviceOrders = new HashSet(0);

    public Cab() {
    }

	
    public Cab(String cabId, VehicleModel vehicleModel, VehicleStatus vehicleStatus, ServiceProvider serviceProvider, VehicleColour vehicleColour) {
        this.cabId = cabId;
        this.vehicleModel = vehicleModel;
        this.vehicleStatus = vehicleStatus;
        this.serviceProvider = serviceProvider;
        this.vehicleColour = vehicleColour;
    }
    public Cab(String cabId, VehicleModel vehicleModel, VehicleStatus vehicleStatus, ServiceProvider serviceProvider, VehicleColour vehicleColour, Double costPerKm, Set serviceOrders) {
       this.cabId = cabId;
       this.vehicleModel = vehicleModel;
       this.vehicleStatus = vehicleStatus;
       this.serviceProvider = serviceProvider;
       this.vehicleColour = vehicleColour;
       this.costPerKm = costPerKm;
       this.serviceOrders = serviceOrders;
    }
   
    public String getCabId() {
        return this.cabId;
    }
    
    public void setCabId(String cabId) {
        this.cabId = cabId;
    }
    public VehicleModel getVehicleModel() {
        return this.vehicleModel;
    }
    
    public void setVehicleModel(VehicleModel vehicleModel) {
        this.vehicleModel = vehicleModel;
    }
    public VehicleStatus getVehicleStatus() {
        return this.vehicleStatus;
    }
    
    public void setVehicleStatus(VehicleStatus vehicleStatus) {
        this.vehicleStatus = vehicleStatus;
    }
    public ServiceProvider getServiceProvider() {
        return this.serviceProvider;
    }
    
    public void setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }
    public VehicleColour getVehicleColour() {
        return this.vehicleColour;
    }
    
    public void setVehicleColour(VehicleColour vehicleColour) {
        this.vehicleColour = vehicleColour;
    }
    public Double getCostPerKm() {
        return this.costPerKm;
    }
    
    public void setCostPerKm(Double costPerKm) {
        this.costPerKm = costPerKm;
    }
    public Set getServiceOrders() {
        return this.serviceOrders;
    }
    
    public void setServiceOrders(Set serviceOrders) {
        this.serviceOrders = serviceOrders;
    }




}


