package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CabDriverLocation generated by hbm2java
 */
public class CabDriverLocation  implements java.io.Serializable {


     private Integer cabDriverLocationId;
     private Double lattitude;
     private Double longitude;
     private Set cabDrivers = new HashSet(0);

    public CabDriverLocation() {
    }

    public CabDriverLocation(Double lattitude, Double longitude, Set cabDrivers) {
       this.lattitude = lattitude;
       this.longitude = longitude;
       this.cabDrivers = cabDrivers;
    }
   
    public Integer getCabDriverLocationId() {
        return this.cabDriverLocationId;
    }
    
    public void setCabDriverLocationId(Integer cabDriverLocationId) {
        this.cabDriverLocationId = cabDriverLocationId;
    }
    public Double getLattitude() {
        return this.lattitude;
    }
    
    public void setLattitude(Double lattitude) {
        this.lattitude = lattitude;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Set getCabDrivers() {
        return this.cabDrivers;
    }
    
    public void setCabDrivers(Set cabDrivers) {
        this.cabDrivers = cabDrivers;
    }




}


