package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer cityId;
     private String googlePlaceId;
     private Set userDetailses = new HashSet(0);
     private Set serviceProviderLocationDetailses = new HashSet(0);
     private Set cabDriverDetailses = new HashSet(0);

    public City() {
    }

    public City(String googlePlaceId, Set userDetailses, Set serviceProviderLocationDetailses, Set cabDriverDetailses) {
       this.googlePlaceId = googlePlaceId;
       this.userDetailses = userDetailses;
       this.serviceProviderLocationDetailses = serviceProviderLocationDetailses;
       this.cabDriverDetailses = cabDriverDetailses;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getGooglePlaceId() {
        return this.googlePlaceId;
    }
    
    public void setGooglePlaceId(String googlePlaceId) {
        this.googlePlaceId = googlePlaceId;
    }
    public Set getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set userDetailses) {
        this.userDetailses = userDetailses;
    }
    public Set getServiceProviderLocationDetailses() {
        return this.serviceProviderLocationDetailses;
    }
    
    public void setServiceProviderLocationDetailses(Set serviceProviderLocationDetailses) {
        this.serviceProviderLocationDetailses = serviceProviderLocationDetailses;
    }
    public Set getCabDriverDetailses() {
        return this.cabDriverDetailses;
    }
    
    public void setCabDriverDetailses(Set cabDriverDetailses) {
        this.cabDriverDetailses = cabDriverDetailses;
    }




}


