package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Destination generated by hbm2java
 */
public class Destination  implements java.io.Serializable {


     private Integer destinationId;
     private Double latitude;
     private Double longitude;
     private Set serviceOrders = new HashSet(0);

    public Destination() {
    }

    public Destination(Double latitude, Double longitude, Set serviceOrders) {
       this.latitude = latitude;
       this.longitude = longitude;
       this.serviceOrders = serviceOrders;
    }
   
    public Integer getDestinationId() {
        return this.destinationId;
    }
    
    public void setDestinationId(Integer destinationId) {
        this.destinationId = destinationId;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Set getServiceOrders() {
        return this.serviceOrders;
    }
    
    public void setServiceOrders(Set serviceOrders) {
        this.serviceOrders = serviceOrders;
    }




}


