package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0



/**
 * DriverContactNo generated by hbm2java
 */
public class DriverContactNo  implements java.io.Serializable {


     private Integer driverCabNoId;
     private CabDriver cabDriver;
     private String contactNo;

    public DriverContactNo() {
    }

	
    public DriverContactNo(CabDriver cabDriver) {
        this.cabDriver = cabDriver;
    }
    public DriverContactNo(CabDriver cabDriver, String contactNo) {
       this.cabDriver = cabDriver;
       this.contactNo = contactNo;
    }
   
    public Integer getDriverCabNoId() {
        return this.driverCabNoId;
    }
    
    public void setDriverCabNoId(Integer driverCabNoId) {
        this.driverCabNoId = driverCabNoId;
    }
    public CabDriver getCabDriver() {
        return this.cabDriver;
    }
    
    public void setCabDriver(CabDriver cabDriver) {
        this.cabDriver = cabDriver;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }




}


