package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DurationMonths generated by hbm2java
 */
public class DurationMonths  implements java.io.Serializable {


     private Integer durationMonthsId;
     private Integer months;
     private Set membershipDurations = new HashSet(0);

    public DurationMonths() {
    }

    public DurationMonths(Integer months, Set membershipDurations) {
       this.months = months;
       this.membershipDurations = membershipDurations;
    }
   
    public Integer getDurationMonthsId() {
        return this.durationMonthsId;
    }
    
    public void setDurationMonthsId(Integer durationMonthsId) {
        this.durationMonthsId = durationMonthsId;
    }
    public Integer getMonths() {
        return this.months;
    }
    
    public void setMonths(Integer months) {
        this.months = months;
    }
    public Set getMembershipDurations() {
        return this.membershipDurations;
    }
    
    public void setMembershipDurations(Set membershipDurations) {
        this.membershipDurations = membershipDurations;
    }




}


