package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Gender generated by hbm2java
 */
public class Gender  implements java.io.Serializable {


     private Integer genderId;
     private String type;
     private Set userDetailses = new HashSet(0);
     private Set adminDetailses = new HashSet(0);

    public Gender() {
    }

    public Gender(String type, Set userDetailses, Set adminDetailses) {
       this.type = type;
       this.userDetailses = userDetailses;
       this.adminDetailses = adminDetailses;
    }
   
    public Integer getGenderId() {
        return this.genderId;
    }
    
    public void setGenderId(Integer genderId) {
        this.genderId = genderId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set userDetailses) {
        this.userDetailses = userDetailses;
    }
    public Set getAdminDetailses() {
        return this.adminDetailses;
    }
    
    public void setAdminDetailses(Set adminDetailses) {
        this.adminDetailses = adminDetailses;
    }




}


