package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Leavingrequest generated by hbm2java
 */
public class Leavingrequest  implements java.io.Serializable {


     private Integer leavingRequestId;
     private Requeststatus requeststatus;
     private CabDriver cabDriver;
     private String reason;
     private Date dateTime;

    public Leavingrequest() {
    }

    public Leavingrequest(Requeststatus requeststatus, CabDriver cabDriver, String reason, Date dateTime) {
       this.requeststatus = requeststatus;
       this.cabDriver = cabDriver;
       this.reason = reason;
       this.dateTime = dateTime;
    }
   
    public Integer getLeavingRequestId() {
        return this.leavingRequestId;
    }
    
    public void setLeavingRequestId(Integer leavingRequestId) {
        this.leavingRequestId = leavingRequestId;
    }
    public Requeststatus getRequeststatus() {
        return this.requeststatus;
    }
    
    public void setRequeststatus(Requeststatus requeststatus) {
        this.requeststatus = requeststatus;
    }
    public CabDriver getCabDriver() {
        return this.cabDriver;
    }
    
    public void setCabDriver(CabDriver cabDriver) {
        this.cabDriver = cabDriver;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


