package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * LocationType generated by hbm2java
 */
public class LocationType  implements java.io.Serializable {


     private Integer locationTypeId;
     private String locationType;
     private Set userLocationses = new HashSet(0);

    public LocationType() {
    }

    public LocationType(String locationType, Set userLocationses) {
       this.locationType = locationType;
       this.userLocationses = userLocationses;
    }
   
    public Integer getLocationTypeId() {
        return this.locationTypeId;
    }
    
    public void setLocationTypeId(Integer locationTypeId) {
        this.locationTypeId = locationTypeId;
    }
    public String getLocationType() {
        return this.locationType;
    }
    
    public void setLocationType(String locationType) {
        this.locationType = locationType;
    }
    public Set getUserLocationses() {
        return this.userLocationses;
    }
    
    public void setUserLocationses(Set userLocationses) {
        this.userLocationses = userLocationses;
    }




}


