package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * LoginStatus generated by hbm2java
 */
public class LoginStatus  implements java.io.Serializable {


     private Integer loginStatusId;
     private String loginStatus;
     private Set loginDetailses = new HashSet(0);

    public LoginStatus() {
    }

    public LoginStatus(String loginStatus, Set loginDetailses) {
       this.loginStatus = loginStatus;
       this.loginDetailses = loginDetailses;
    }
   
    public Integer getLoginStatusId() {
        return this.loginStatusId;
    }
    
    public void setLoginStatusId(Integer loginStatusId) {
        this.loginStatusId = loginStatusId;
    }
    public String getLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }
    public Set getLoginDetailses() {
        return this.loginDetailses;
    }
    
    public void setLoginDetailses(Set loginDetailses) {
        this.loginDetailses = loginDetailses;
    }




}


