package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LoginDetails generated by hbm2java
 */
public class LoginDetails  implements java.io.Serializable {


     private Integer loginDetailsId;
     private UserType userType;
     private LoginStatus loginStatus;
     private String email;
     private String password;
     private Date lastUpdate;
     private Set users = new HashSet(0);
     private Set cabDrivers = new HashSet(0);
     private Set administrators = new HashSet(0);
     private Set paymentOptions = new HashSet(0);
     private Set serviceProviders = new HashSet(0);
     private Set messagesForMsgFrom = new HashSet(0);
     private Set messagesForMsgTo = new HashSet(0);

    public LoginDetails() {
    }

	
    public LoginDetails(UserType userType, LoginStatus loginStatus) {
        this.userType = userType;
        this.loginStatus = loginStatus;
    }
    public LoginDetails(UserType userType, LoginStatus loginStatus, String email, String password, Date lastUpdate, Set users, Set cabDrivers, Set administrators, Set paymentOptions, Set serviceProviders, Set messagesForMsgFrom, Set messagesForMsgTo) {
       this.userType = userType;
       this.loginStatus = loginStatus;
       this.email = email;
       this.password = password;
       this.lastUpdate = lastUpdate;
       this.users = users;
       this.cabDrivers = cabDrivers;
       this.administrators = administrators;
       this.paymentOptions = paymentOptions;
       this.serviceProviders = serviceProviders;
       this.messagesForMsgFrom = messagesForMsgFrom;
       this.messagesForMsgTo = messagesForMsgTo;
    }
   
    public Integer getLoginDetailsId() {
        return this.loginDetailsId;
    }
    
    public void setLoginDetailsId(Integer loginDetailsId) {
        this.loginDetailsId = loginDetailsId;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public LoginStatus getLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(LoginStatus loginStatus) {
        this.loginStatus = loginStatus;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getCabDrivers() {
        return this.cabDrivers;
    }
    
    public void setCabDrivers(Set cabDrivers) {
        this.cabDrivers = cabDrivers;
    }
    public Set getAdministrators() {
        return this.administrators;
    }
    
    public void setAdministrators(Set administrators) {
        this.administrators = administrators;
    }
    public Set getPaymentOptions() {
        return this.paymentOptions;
    }
    
    public void setPaymentOptions(Set paymentOptions) {
        this.paymentOptions = paymentOptions;
    }
    public Set getServiceProviders() {
        return this.serviceProviders;
    }
    
    public void setServiceProviders(Set serviceProviders) {
        this.serviceProviders = serviceProviders;
    }
    public Set getMessagesForMsgFrom() {
        return this.messagesForMsgFrom;
    }
    
    public void setMessagesForMsgFrom(Set messagesForMsgFrom) {
        this.messagesForMsgFrom = messagesForMsgFrom;
    }
    public Set getMessagesForMsgTo() {
        return this.messagesForMsgTo;
    }
    
    public void setMessagesForMsgTo(Set messagesForMsgTo) {
        this.messagesForMsgTo = messagesForMsgTo;
    }




}


