package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Logo generated by hbm2java
 */
public class Logo  implements java.io.Serializable {


     private Integer logoId;
     private String logoUrl;
     private Set serviceProviders = new HashSet(0);

    public Logo() {
    }

    public Logo(String logoUrl, Set serviceProviders) {
       this.logoUrl = logoUrl;
       this.serviceProviders = serviceProviders;
    }
   
    public Integer getLogoId() {
        return this.logoId;
    }
    
    public void setLogoId(Integer logoId) {
        this.logoId = logoId;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public Set getServiceProviders() {
        return this.serviceProviders;
    }
    
    public void setServiceProviders(Set serviceProviders) {
        this.serviceProviders = serviceProviders;
    }




}


