package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MembershipUpgradeHistory generated by hbm2java
 */
public class MembershipUpgradeHistory  implements java.io.Serializable {


     private Integer membershipUpgradeId;
     private ServiceProvider serviceProvider;
     private MembershipDuration membershipDuration;
     private MembershipPlan membershipPlan;
     private Date activatedDatetime;
     private Date expiresDatetime;
     private Set membershipPaymentHistories = new HashSet(0);

    public MembershipUpgradeHistory() {
    }

	
    public MembershipUpgradeHistory(ServiceProvider serviceProvider, MembershipDuration membershipDuration, MembershipPlan membershipPlan) {
        this.serviceProvider = serviceProvider;
        this.membershipDuration = membershipDuration;
        this.membershipPlan = membershipPlan;
    }
    public MembershipUpgradeHistory(ServiceProvider serviceProvider, MembershipDuration membershipDuration, MembershipPlan membershipPlan, Date activatedDatetime, Date expiresDatetime, Set membershipPaymentHistories) {
       this.serviceProvider = serviceProvider;
       this.membershipDuration = membershipDuration;
       this.membershipPlan = membershipPlan;
       this.activatedDatetime = activatedDatetime;
       this.expiresDatetime = expiresDatetime;
       this.membershipPaymentHistories = membershipPaymentHistories;
    }
   
    public Integer getMembershipUpgradeId() {
        return this.membershipUpgradeId;
    }
    
    public void setMembershipUpgradeId(Integer membershipUpgradeId) {
        this.membershipUpgradeId = membershipUpgradeId;
    }
    public ServiceProvider getServiceProvider() {
        return this.serviceProvider;
    }
    
    public void setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }
    public MembershipDuration getMembershipDuration() {
        return this.membershipDuration;
    }
    
    public void setMembershipDuration(MembershipDuration membershipDuration) {
        this.membershipDuration = membershipDuration;
    }
    public MembershipPlan getMembershipPlan() {
        return this.membershipPlan;
    }
    
    public void setMembershipPlan(MembershipPlan membershipPlan) {
        this.membershipPlan = membershipPlan;
    }
    public Date getActivatedDatetime() {
        return this.activatedDatetime;
    }
    
    public void setActivatedDatetime(Date activatedDatetime) {
        this.activatedDatetime = activatedDatetime;
    }
    public Date getExpiresDatetime() {
        return this.expiresDatetime;
    }
    
    public void setExpiresDatetime(Date expiresDatetime) {
        this.expiresDatetime = expiresDatetime;
    }
    public Set getMembershipPaymentHistories() {
        return this.membershipPaymentHistories;
    }
    
    public void setMembershipPaymentHistories(Set membershipPaymentHistories) {
        this.membershipPaymentHistories = membershipPaymentHistories;
    }




}


