package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MembershipStatus generated by hbm2java
 */
public class MembershipStatus  implements java.io.Serializable {


     private Integer membershipStatusId;
     private String membershipStatus;
     private Set serviceProviders = new HashSet(0);

    public MembershipStatus() {
    }

    public MembershipStatus(String membershipStatus, Set serviceProviders) {
       this.membershipStatus = membershipStatus;
       this.serviceProviders = serviceProviders;
    }
   
    public Integer getMembershipStatusId() {
        return this.membershipStatusId;
    }
    
    public void setMembershipStatusId(Integer membershipStatusId) {
        this.membershipStatusId = membershipStatusId;
    }
    public String getMembershipStatus() {
        return this.membershipStatus;
    }
    
    public void setMembershipStatus(String membershipStatus) {
        this.membershipStatus = membershipStatus;
    }
    public Set getServiceProviders() {
        return this.serviceProviders;
    }
    
    public void setServiceProviders(Set serviceProviders) {
        this.serviceProviders = serviceProviders;
    }




}


