package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * MembershipPaymentHistory generated by hbm2java
 */
public class MembershipPaymentHistory  implements java.io.Serializable {


     private Integer membershipPaymentId;
     private PaymentStatus paymentStatus;
     private MembershipUpgradeHistory membershipUpgradeHistory;
     private String paypalTransactionId;
     private Double paidAmount;
     private Double paypalFee;
     private Double currencyRate;
     private Date dateTime;

    public MembershipPaymentHistory() {
    }

	
    public MembershipPaymentHistory(PaymentStatus paymentStatus, MembershipUpgradeHistory membershipUpgradeHistory) {
        this.paymentStatus = paymentStatus;
        this.membershipUpgradeHistory = membershipUpgradeHistory;
    }
    public MembershipPaymentHistory(PaymentStatus paymentStatus, MembershipUpgradeHistory membershipUpgradeHistory, String paypalTransactionId, Double paidAmount, Double paypalFee, Double currencyRate, Date dateTime) {
       this.paymentStatus = paymentStatus;
       this.membershipUpgradeHistory = membershipUpgradeHistory;
       this.paypalTransactionId = paypalTransactionId;
       this.paidAmount = paidAmount;
       this.paypalFee = paypalFee;
       this.currencyRate = currencyRate;
       this.dateTime = dateTime;
    }
   
    public Integer getMembershipPaymentId() {
        return this.membershipPaymentId;
    }
    
    public void setMembershipPaymentId(Integer membershipPaymentId) {
        this.membershipPaymentId = membershipPaymentId;
    }
    public PaymentStatus getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public MembershipUpgradeHistory getMembershipUpgradeHistory() {
        return this.membershipUpgradeHistory;
    }
    
    public void setMembershipUpgradeHistory(MembershipUpgradeHistory membershipUpgradeHistory) {
        this.membershipUpgradeHistory = membershipUpgradeHistory;
    }
    public String getPaypalTransactionId() {
        return this.paypalTransactionId;
    }
    
    public void setPaypalTransactionId(String paypalTransactionId) {
        this.paypalTransactionId = paypalTransactionId;
    }
    public Double getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(Double paidAmount) {
        this.paidAmount = paidAmount;
    }
    public Double getPaypalFee() {
        return this.paypalFee;
    }
    
    public void setPaypalFee(Double paypalFee) {
        this.paypalFee = paypalFee;
    }
    public Double getCurrencyRate() {
        return this.currencyRate;
    }
    
    public void setCurrencyRate(Double currencyRate) {
        this.currencyRate = currencyRate;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


