package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MembershipDuration generated by hbm2java
 */
public class MembershipDuration  implements java.io.Serializable {


     private Integer membershipDurationId;
     private DurationMonths durationMonths;
     private MembershipPlan membershipPlan;
     private Double durationFee;
     private Set membershipUpgradeHistories = new HashSet(0);

    public MembershipDuration() {
    }

	
    public MembershipDuration(DurationMonths durationMonths, MembershipPlan membershipPlan) {
        this.durationMonths = durationMonths;
        this.membershipPlan = membershipPlan;
    }
    public MembershipDuration(DurationMonths durationMonths, MembershipPlan membershipPlan, Double durationFee, Set membershipUpgradeHistories) {
       this.durationMonths = durationMonths;
       this.membershipPlan = membershipPlan;
       this.durationFee = durationFee;
       this.membershipUpgradeHistories = membershipUpgradeHistories;
    }
   
    public Integer getMembershipDurationId() {
        return this.membershipDurationId;
    }
    
    public void setMembershipDurationId(Integer membershipDurationId) {
        this.membershipDurationId = membershipDurationId;
    }
    public DurationMonths getDurationMonths() {
        return this.durationMonths;
    }
    
    public void setDurationMonths(DurationMonths durationMonths) {
        this.durationMonths = durationMonths;
    }
    public MembershipPlan getMembershipPlan() {
        return this.membershipPlan;
    }
    
    public void setMembershipPlan(MembershipPlan membershipPlan) {
        this.membershipPlan = membershipPlan;
    }
    public Double getDurationFee() {
        return this.durationFee;
    }
    
    public void setDurationFee(Double durationFee) {
        this.durationFee = durationFee;
    }
    public Set getMembershipUpgradeHistories() {
        return this.membershipUpgradeHistories;
    }
    
    public void setMembershipUpgradeHistories(Set membershipUpgradeHistories) {
        this.membershipUpgradeHistories = membershipUpgradeHistories;
    }




}


