package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer msgId;
     private MsgType msgType;
     private MsgStatus msgStatus;
     private Message message;
     private MsgPriority msgPriority;
     private LoginDetails loginDetailsByMsgFrom;
     private LoginDetails loginDetailsByMsgTo;
     private String subject;
     private String content;
     private Date dateTime;
     private Set messages = new HashSet(0);

    public Message() {
    }

	
    public Message(MsgType msgType, MsgStatus msgStatus, MsgPriority msgPriority) {
        this.msgType = msgType;
        this.msgStatus = msgStatus;
        this.msgPriority = msgPriority;
    }
    public Message(MsgType msgType, MsgStatus msgStatus, Message message, MsgPriority msgPriority, LoginDetails loginDetailsByMsgFrom, LoginDetails loginDetailsByMsgTo, String subject, String content, Date dateTime, Set messages) {
       this.msgType = msgType;
       this.msgStatus = msgStatus;
       this.message = message;
       this.msgPriority = msgPriority;
       this.loginDetailsByMsgFrom = loginDetailsByMsgFrom;
       this.loginDetailsByMsgTo = loginDetailsByMsgTo;
       this.subject = subject;
       this.content = content;
       this.dateTime = dateTime;
       this.messages = messages;
    }
   
    public Integer getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }
    public MsgType getMsgType() {
        return this.msgType;
    }
    
    public void setMsgType(MsgType msgType) {
        this.msgType = msgType;
    }
    public MsgStatus getMsgStatus() {
        return this.msgStatus;
    }
    
    public void setMsgStatus(MsgStatus msgStatus) {
        this.msgStatus = msgStatus;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }
    public MsgPriority getMsgPriority() {
        return this.msgPriority;
    }
    
    public void setMsgPriority(MsgPriority msgPriority) {
        this.msgPriority = msgPriority;
    }
    public LoginDetails getLoginDetailsByMsgFrom() {
        return this.loginDetailsByMsgFrom;
    }
    
    public void setLoginDetailsByMsgFrom(LoginDetails loginDetailsByMsgFrom) {
        this.loginDetailsByMsgFrom = loginDetailsByMsgFrom;
    }
    public LoginDetails getLoginDetailsByMsgTo() {
        return this.loginDetailsByMsgTo;
    }
    
    public void setLoginDetailsByMsgTo(LoginDetails loginDetailsByMsgTo) {
        this.loginDetailsByMsgTo = loginDetailsByMsgTo;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }




}


