package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MsgStatus generated by hbm2java
 */
public class MsgStatus  implements java.io.Serializable {


     private Integer msgStatusId;
     private String msgStatus;
     private Set messages = new HashSet(0);

    public MsgStatus() {
    }

    public MsgStatus(String msgStatus, Set messages) {
       this.msgStatus = msgStatus;
       this.messages = messages;
    }
   
    public Integer getMsgStatusId() {
        return this.msgStatusId;
    }
    
    public void setMsgStatusId(Integer msgStatusId) {
        this.msgStatusId = msgStatusId;
    }
    public String getMsgStatus() {
        return this.msgStatus;
    }
    
    public void setMsgStatus(String msgStatus) {
        this.msgStatus = msgStatus;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }




}


