package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus  implements java.io.Serializable {


     private Integer orderStatusId;
     private String orderStatus;
     private Set serviceOrders = new HashSet(0);

    public OrderStatus() {
    }

    public OrderStatus(String orderStatus, Set serviceOrders) {
       this.orderStatus = orderStatus;
       this.serviceOrders = serviceOrders;
    }
   
    public Integer getOrderStatusId() {
        return this.orderStatusId;
    }
    
    public void setOrderStatusId(Integer orderStatusId) {
        this.orderStatusId = orderStatusId;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Set getServiceOrders() {
        return this.serviceOrders;
    }
    
    public void setServiceOrders(Set serviceOrders) {
        this.serviceOrders = serviceOrders;
    }




}


