package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * OutsidePayout generated by hbm2java
 */
public class OutsidePayout  implements java.io.Serializable {


     private Integer outsidePayoutId;
     private Administrator administrator;
     private PayoutStatus payoutStatus;
     private ServiceProvider serviceProvider;
     private Date dateTime;
     private String description;
     private Double payoutAmount;

    public OutsidePayout() {
    }

	
    public OutsidePayout(Administrator administrator, PayoutStatus payoutStatus, ServiceProvider serviceProvider) {
        this.administrator = administrator;
        this.payoutStatus = payoutStatus;
        this.serviceProvider = serviceProvider;
    }
    public OutsidePayout(Administrator administrator, PayoutStatus payoutStatus, ServiceProvider serviceProvider, Date dateTime, String description, Double payoutAmount) {
       this.administrator = administrator;
       this.payoutStatus = payoutStatus;
       this.serviceProvider = serviceProvider;
       this.dateTime = dateTime;
       this.description = description;
       this.payoutAmount = payoutAmount;
    }
   
    public Integer getOutsidePayoutId() {
        return this.outsidePayoutId;
    }
    
    public void setOutsidePayoutId(Integer outsidePayoutId) {
        this.outsidePayoutId = outsidePayoutId;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }
    public PayoutStatus getPayoutStatus() {
        return this.payoutStatus;
    }
    
    public void setPayoutStatus(PayoutStatus payoutStatus) {
        this.payoutStatus = payoutStatus;
    }
    public ServiceProvider getServiceProvider() {
        return this.serviceProvider;
    }
    
    public void setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getPayoutAmount() {
        return this.payoutAmount;
    }
    
    public void setPayoutAmount(Double payoutAmount) {
        this.payoutAmount = payoutAmount;
    }




}


