package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PaidHistory generated by hbm2java
 */
public class PaidHistory  implements java.io.Serializable {


     private Integer paidHistoryId;
     private PaymentMethod paymentMethod;
     private PaymentStatus paymentStatus;
     private PayLaterService payLaterService;
     private double paidAmount;
     private double dueAmount;
     private Date dateTime;

    public PaidHistory() {
    }

	
    public PaidHistory(PaymentMethod paymentMethod, PaymentStatus paymentStatus, PayLaterService payLaterService, double paidAmount, double dueAmount) {
        this.paymentMethod = paymentMethod;
        this.paymentStatus = paymentStatus;
        this.payLaterService = payLaterService;
        this.paidAmount = paidAmount;
        this.dueAmount = dueAmount;
    }
    public PaidHistory(PaymentMethod paymentMethod, PaymentStatus paymentStatus, PayLaterService payLaterService, double paidAmount, double dueAmount, Date dateTime) {
       this.paymentMethod = paymentMethod;
       this.paymentStatus = paymentStatus;
       this.payLaterService = payLaterService;
       this.paidAmount = paidAmount;
       this.dueAmount = dueAmount;
       this.dateTime = dateTime;
    }
   
    public Integer getPaidHistoryId() {
        return this.paidHistoryId;
    }
    
    public void setPaidHistoryId(Integer paidHistoryId) {
        this.paidHistoryId = paidHistoryId;
    }
    public PaymentMethod getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public PaymentStatus getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public PayLaterService getPayLaterService() {
        return this.payLaterService;
    }
    
    public void setPayLaterService(PayLaterService payLaterService) {
        this.payLaterService = payLaterService;
    }
    public double getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(double paidAmount) {
        this.paidAmount = paidAmount;
    }
    public double getDueAmount() {
        return this.dueAmount;
    }
    
    public void setDueAmount(double dueAmount) {
        this.dueAmount = dueAmount;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


