package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PayLaterItem generated by hbm2java
 */
public class PayLaterItem  implements java.io.Serializable {


     private Integer payLaterItemId;
     private PayLaterService payLaterService;
     private ServiceInvoice serviceInvoice;
     private Date dateTime;
     private boolean isPaid;

    public PayLaterItem() {
    }

	
    public PayLaterItem(PayLaterService payLaterService, ServiceInvoice serviceInvoice, boolean isPaid) {
        this.payLaterService = payLaterService;
        this.serviceInvoice = serviceInvoice;
        this.isPaid = isPaid;
    }
    public PayLaterItem(PayLaterService payLaterService, ServiceInvoice serviceInvoice, Date dateTime, boolean isPaid) {
       this.payLaterService = payLaterService;
       this.serviceInvoice = serviceInvoice;
       this.dateTime = dateTime;
       this.isPaid = isPaid;
    }
   
    public Integer getPayLaterItemId() {
        return this.payLaterItemId;
    }
    
    public void setPayLaterItemId(Integer payLaterItemId) {
        this.payLaterItemId = payLaterItemId;
    }
    public PayLaterService getPayLaterService() {
        return this.payLaterService;
    }
    
    public void setPayLaterService(PayLaterService payLaterService) {
        this.payLaterService = payLaterService;
    }
    public ServiceInvoice getServiceInvoice() {
        return this.serviceInvoice;
    }
    
    public void setServiceInvoice(ServiceInvoice serviceInvoice) {
        this.serviceInvoice = serviceInvoice;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public boolean isIsPaid() {
        return this.isPaid;
    }
    
    public void setIsPaid(boolean isPaid) {
        this.isPaid = isPaid;
    }




}


