package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentInfoStatus generated by hbm2java
 */
public class PaymentInfoStatus  implements java.io.Serializable {


     private Integer paymentInfoStatusId;
     private String paymentInfoStatus;
     private Set paymentOptions = new HashSet(0);

    public PaymentInfoStatus() {
    }

    public PaymentInfoStatus(String paymentInfoStatus, Set paymentOptions) {
       this.paymentInfoStatus = paymentInfoStatus;
       this.paymentOptions = paymentOptions;
    }
   
    public Integer getPaymentInfoStatusId() {
        return this.paymentInfoStatusId;
    }
    
    public void setPaymentInfoStatusId(Integer paymentInfoStatusId) {
        this.paymentInfoStatusId = paymentInfoStatusId;
    }
    public String getPaymentInfoStatus() {
        return this.paymentInfoStatus;
    }
    
    public void setPaymentInfoStatus(String paymentInfoStatus) {
        this.paymentInfoStatus = paymentInfoStatus;
    }
    public Set getPaymentOptions() {
        return this.paymentOptions;
    }
    
    public void setPaymentOptions(Set paymentOptions) {
        this.paymentOptions = paymentOptions;
    }




}


