package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PayoutStatus generated by hbm2java
 */
public class PayoutStatus  implements java.io.Serializable {


     private Integer payoutStatusId;
     private String payoutStatus;
     private Set outsidePayouts = new HashSet(0);

    public PayoutStatus() {
    }

    public PayoutStatus(String payoutStatus, Set outsidePayouts) {
       this.payoutStatus = payoutStatus;
       this.outsidePayouts = outsidePayouts;
    }
   
    public Integer getPayoutStatusId() {
        return this.payoutStatusId;
    }
    
    public void setPayoutStatusId(Integer payoutStatusId) {
        this.payoutStatusId = payoutStatusId;
    }
    public String getPayoutStatus() {
        return this.payoutStatus;
    }
    
    public void setPayoutStatus(String payoutStatus) {
        this.payoutStatus = payoutStatus;
    }
    public Set getOutsidePayouts() {
        return this.outsidePayouts;
    }
    
    public void setOutsidePayouts(Set outsidePayouts) {
        this.outsidePayouts = outsidePayouts;
    }




}


