package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PriorityOrder generated by hbm2java
 */
public class PriorityOrder  implements java.io.Serializable {


     private Integer priorityOrderId;
     private String priority;
     private Set paymentOptions = new HashSet(0);

    public PriorityOrder() {
    }

    public PriorityOrder(String priority, Set paymentOptions) {
       this.priority = priority;
       this.paymentOptions = paymentOptions;
    }
   
    public Integer getPriorityOrderId() {
        return this.priorityOrderId;
    }
    
    public void setPriorityOrderId(Integer priorityOrderId) {
        this.priorityOrderId = priorityOrderId;
    }
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }
    public Set getPaymentOptions() {
        return this.paymentOptions;
    }
    
    public void setPaymentOptions(Set paymentOptions) {
        this.paymentOptions = paymentOptions;
    }




}


