package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ProfilePicture generated by hbm2java
 */
public class ProfilePicture  implements java.io.Serializable {


     private Integer profilePicId;
     private String profilePicUrl;
     private Set userDetailses = new HashSet(0);
     private Set cabDrivers = new HashSet(0);
     private Set administrators = new HashSet(0);

    public ProfilePicture() {
    }

    public ProfilePicture(String profilePicUrl, Set userDetailses, Set cabDrivers, Set administrators) {
       this.profilePicUrl = profilePicUrl;
       this.userDetailses = userDetailses;
       this.cabDrivers = cabDrivers;
       this.administrators = administrators;
    }
   
    public Integer getProfilePicId() {
        return this.profilePicId;
    }
    
    public void setProfilePicId(Integer profilePicId) {
        this.profilePicId = profilePicId;
    }
    public String getProfilePicUrl() {
        return this.profilePicUrl;
    }
    
    public void setProfilePicUrl(String profilePicUrl) {
        this.profilePicUrl = profilePicUrl;
    }
    public Set getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set userDetailses) {
        this.userDetailses = userDetailses;
    }
    public Set getCabDrivers() {
        return this.cabDrivers;
    }
    
    public void setCabDrivers(Set cabDrivers) {
        this.cabDrivers = cabDrivers;
    }
    public Set getAdministrators() {
        return this.administrators;
    }
    
    public void setAdministrators(Set administrators) {
        this.administrators = administrators;
    }




}


