package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ServiceOrder generated by hbm2java
 */
public class ServiceOrder  implements java.io.Serializable {


     private Integer serviceOrderId;
     private OrderStatus orderStatus;
     private Destination destination;
     private ServiceProvider serviceProvider;
     private ServiceInvoice serviceInvoice;
     private CabDriver cabDriver;
     private StartPoint startPoint;
     private Cab cab;
     private Double km;
     private Double costPerKm;
     private Double total;
     private Date orderedAt;
     private Date scheduledDateTime;

    public ServiceOrder() {
    }

	
    public ServiceOrder(OrderStatus orderStatus, Destination destination, ServiceProvider serviceProvider, ServiceInvoice serviceInvoice, StartPoint startPoint) {
        this.orderStatus = orderStatus;
        this.destination = destination;
        this.serviceProvider = serviceProvider;
        this.serviceInvoice = serviceInvoice;
        this.startPoint = startPoint;
    }
    public ServiceOrder(OrderStatus orderStatus, Destination destination, ServiceProvider serviceProvider, ServiceInvoice serviceInvoice, CabDriver cabDriver, StartPoint startPoint, Cab cab, Double km, Double costPerKm, Double total, Date orderedAt, Date scheduledDateTime) {
       this.orderStatus = orderStatus;
       this.destination = destination;
       this.serviceProvider = serviceProvider;
       this.serviceInvoice = serviceInvoice;
       this.cabDriver = cabDriver;
       this.startPoint = startPoint;
       this.cab = cab;
       this.km = km;
       this.costPerKm = costPerKm;
       this.total = total;
       this.orderedAt = orderedAt;
       this.scheduledDateTime = scheduledDateTime;
    }
   
    public Integer getServiceOrderId() {
        return this.serviceOrderId;
    }
    
    public void setServiceOrderId(Integer serviceOrderId) {
        this.serviceOrderId = serviceOrderId;
    }
    public OrderStatus getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(OrderStatus orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Destination getDestination() {
        return this.destination;
    }
    
    public void setDestination(Destination destination) {
        this.destination = destination;
    }
    public ServiceProvider getServiceProvider() {
        return this.serviceProvider;
    }
    
    public void setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }
    public ServiceInvoice getServiceInvoice() {
        return this.serviceInvoice;
    }
    
    public void setServiceInvoice(ServiceInvoice serviceInvoice) {
        this.serviceInvoice = serviceInvoice;
    }
    public CabDriver getCabDriver() {
        return this.cabDriver;
    }
    
    public void setCabDriver(CabDriver cabDriver) {
        this.cabDriver = cabDriver;
    }
    public StartPoint getStartPoint() {
        return this.startPoint;
    }
    
    public void setStartPoint(StartPoint startPoint) {
        this.startPoint = startPoint;
    }
    public Cab getCab() {
        return this.cab;
    }
    
    public void setCab(Cab cab) {
        this.cab = cab;
    }
    public Double getKm() {
        return this.km;
    }
    
    public void setKm(Double km) {
        this.km = km;
    }
    public Double getCostPerKm() {
        return this.costPerKm;
    }
    
    public void setCostPerKm(Double costPerKm) {
        this.costPerKm = costPerKm;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getOrderedAt() {
        return this.orderedAt;
    }
    
    public void setOrderedAt(Date orderedAt) {
        this.orderedAt = orderedAt;
    }
    public Date getScheduledDateTime() {
        return this.scheduledDateTime;
    }
    
    public void setScheduledDateTime(Date scheduledDateTime) {
        this.scheduledDateTime = scheduledDateTime;
    }




}


