package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ServiceDuration generated by hbm2java
 */
public class ServiceDuration  implements java.io.Serializable {


     private Integer serviceDurationId;
     private String description;
     private int value;
     private Set payLaterServices = new HashSet(0);

    public ServiceDuration() {
    }

	
    public ServiceDuration(String description, int value) {
        this.description = description;
        this.value = value;
    }
    public ServiceDuration(String description, int value, Set payLaterServices) {
       this.description = description;
       this.value = value;
       this.payLaterServices = payLaterServices;
    }
   
    public Integer getServiceDurationId() {
        return this.serviceDurationId;
    }
    
    public void setServiceDurationId(Integer serviceDurationId) {
        this.serviceDurationId = serviceDurationId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }
    public Set getPayLaterServices() {
        return this.payLaterServices;
    }
    
    public void setPayLaterServices(Set payLaterServices) {
        this.payLaterServices = payLaterServices;
    }




}


