package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ServiceInvoiceStatus generated by hbm2java
 */
public class ServiceInvoiceStatus  implements java.io.Serializable {


     private Integer serviceInvoiceStatusId;
     private String serviceInvoiceStatus;
     private Set serviceInvoices = new HashSet(0);

    public ServiceInvoiceStatus() {
    }

    public ServiceInvoiceStatus(String serviceInvoiceStatus, Set serviceInvoices) {
       this.serviceInvoiceStatus = serviceInvoiceStatus;
       this.serviceInvoices = serviceInvoices;
    }
   
    public Integer getServiceInvoiceStatusId() {
        return this.serviceInvoiceStatusId;
    }
    
    public void setServiceInvoiceStatusId(Integer serviceInvoiceStatusId) {
        this.serviceInvoiceStatusId = serviceInvoiceStatusId;
    }
    public String getServiceInvoiceStatus() {
        return this.serviceInvoiceStatus;
    }
    
    public void setServiceInvoiceStatus(String serviceInvoiceStatus) {
        this.serviceInvoiceStatus = serviceInvoiceStatus;
    }
    public Set getServiceInvoices() {
        return this.serviceInvoices;
    }
    
    public void setServiceInvoices(Set serviceInvoices) {
        this.serviceInvoices = serviceInvoices;
    }




}


