package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ServiceProvider generated by hbm2java
 */
public class ServiceProvider  implements java.io.Serializable {


     private Integer serviceProviderId;
     private ServiceProviderLocationDetails serviceProviderLocationDetails;
     private LoginDetails loginDetails;
     private MembershipStatus membershipStatus;
     private ServiceDetails serviceDetails;
     private Logo logo;
     private String serviceProviderName;
     private String contactNo;
     private Set serviceOrders = new HashSet(0);
     private Set outsidePayouts = new HashSet(0);
     private Set payLaterServices = new HashSet(0);
     private Set cabs = new HashSet(0);
     private Set cabDrivers = new HashSet(0);
     private Set membershipUpgradeHistories = new HashSet(0);

    public ServiceProvider() {
    }

	
    public ServiceProvider(LoginDetails loginDetails, Logo logo) {
        this.loginDetails = loginDetails;
        this.logo = logo;
    }
    public ServiceProvider(ServiceProviderLocationDetails serviceProviderLocationDetails, LoginDetails loginDetails, MembershipStatus membershipStatus, ServiceDetails serviceDetails, Logo logo, String serviceProviderName, String contactNo, Set serviceOrders, Set outsidePayouts, Set payLaterServices, Set cabs, Set cabDrivers, Set membershipUpgradeHistories) {
       this.serviceProviderLocationDetails = serviceProviderLocationDetails;
       this.loginDetails = loginDetails;
       this.membershipStatus = membershipStatus;
       this.serviceDetails = serviceDetails;
       this.logo = logo;
       this.serviceProviderName = serviceProviderName;
       this.contactNo = contactNo;
       this.serviceOrders = serviceOrders;
       this.outsidePayouts = outsidePayouts;
       this.payLaterServices = payLaterServices;
       this.cabs = cabs;
       this.cabDrivers = cabDrivers;
       this.membershipUpgradeHistories = membershipUpgradeHistories;
    }
   
    public Integer getServiceProviderId() {
        return this.serviceProviderId;
    }
    
    public void setServiceProviderId(Integer serviceProviderId) {
        this.serviceProviderId = serviceProviderId;
    }
    public ServiceProviderLocationDetails getServiceProviderLocationDetails() {
        return this.serviceProviderLocationDetails;
    }
    
    public void setServiceProviderLocationDetails(ServiceProviderLocationDetails serviceProviderLocationDetails) {
        this.serviceProviderLocationDetails = serviceProviderLocationDetails;
    }
    public LoginDetails getLoginDetails() {
        return this.loginDetails;
    }
    
    public void setLoginDetails(LoginDetails loginDetails) {
        this.loginDetails = loginDetails;
    }
    public MembershipStatus getMembershipStatus() {
        return this.membershipStatus;
    }
    
    public void setMembershipStatus(MembershipStatus membershipStatus) {
        this.membershipStatus = membershipStatus;
    }
    public ServiceDetails getServiceDetails() {
        return this.serviceDetails;
    }
    
    public void setServiceDetails(ServiceDetails serviceDetails) {
        this.serviceDetails = serviceDetails;
    }
    public Logo getLogo() {
        return this.logo;
    }
    
    public void setLogo(Logo logo) {
        this.logo = logo;
    }
    public String getServiceProviderName() {
        return this.serviceProviderName;
    }
    
    public void setServiceProviderName(String serviceProviderName) {
        this.serviceProviderName = serviceProviderName;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public Set getServiceOrders() {
        return this.serviceOrders;
    }
    
    public void setServiceOrders(Set serviceOrders) {
        this.serviceOrders = serviceOrders;
    }
    public Set getOutsidePayouts() {
        return this.outsidePayouts;
    }
    
    public void setOutsidePayouts(Set outsidePayouts) {
        this.outsidePayouts = outsidePayouts;
    }
    public Set getPayLaterServices() {
        return this.payLaterServices;
    }
    
    public void setPayLaterServices(Set payLaterServices) {
        this.payLaterServices = payLaterServices;
    }
    public Set getCabs() {
        return this.cabs;
    }
    
    public void setCabs(Set cabs) {
        this.cabs = cabs;
    }
    public Set getCabDrivers() {
        return this.cabDrivers;
    }
    
    public void setCabDrivers(Set cabDrivers) {
        this.cabDrivers = cabDrivers;
    }
    public Set getMembershipUpgradeHistories() {
        return this.membershipUpgradeHistories;
    }
    
    public void setMembershipUpgradeHistories(Set membershipUpgradeHistories) {
        this.membershipUpgradeHistories = membershipUpgradeHistories;
    }




}


