package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ServicePaymentHistory generated by hbm2java
 */
public class ServicePaymentHistory  implements java.io.Serializable {


     private Integer servicePaymentId;
     private PaymentMethod paymentMethod;
     private ServiceInvoice serviceInvoice;
     private PaymentStatus paymentStatus;
     private String transactionId;
     private Double currencyRate;
     private Double paidAmount;
     private Double paypalFee;
     private Double dueAmount;
     private Date dateTime;

    public ServicePaymentHistory() {
    }

	
    public ServicePaymentHistory(PaymentMethod paymentMethod, ServiceInvoice serviceInvoice, PaymentStatus paymentStatus) {
        this.paymentMethod = paymentMethod;
        this.serviceInvoice = serviceInvoice;
        this.paymentStatus = paymentStatus;
    }
    public ServicePaymentHistory(PaymentMethod paymentMethod, ServiceInvoice serviceInvoice, PaymentStatus paymentStatus, String transactionId, Double currencyRate, Double paidAmount, Double paypalFee, Double dueAmount, Date dateTime) {
       this.paymentMethod = paymentMethod;
       this.serviceInvoice = serviceInvoice;
       this.paymentStatus = paymentStatus;
       this.transactionId = transactionId;
       this.currencyRate = currencyRate;
       this.paidAmount = paidAmount;
       this.paypalFee = paypalFee;
       this.dueAmount = dueAmount;
       this.dateTime = dateTime;
    }
   
    public Integer getServicePaymentId() {
        return this.servicePaymentId;
    }
    
    public void setServicePaymentId(Integer servicePaymentId) {
        this.servicePaymentId = servicePaymentId;
    }
    public PaymentMethod getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public ServiceInvoice getServiceInvoice() {
        return this.serviceInvoice;
    }
    
    public void setServiceInvoice(ServiceInvoice serviceInvoice) {
        this.serviceInvoice = serviceInvoice;
    }
    public PaymentStatus getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }
    public Double getCurrencyRate() {
        return this.currencyRate;
    }
    
    public void setCurrencyRate(Double currencyRate) {
        this.currencyRate = currencyRate;
    }
    public Double getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(Double paidAmount) {
        this.paidAmount = paidAmount;
    }
    public Double getPaypalFee() {
        return this.paypalFee;
    }
    
    public void setPaypalFee(Double paypalFee) {
        this.paypalFee = paypalFee;
    }
    public Double getDueAmount() {
        return this.dueAmount;
    }
    
    public void setDueAmount(Double dueAmount) {
        this.dueAmount = dueAmount;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


