package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceInvoice generated by hbm2java
 */
public class ServiceInvoice  implements java.io.Serializable {


     private Integer serviceInvoiceId;
     private ServiceInvoiceStatus serviceInvoiceStatus;
     private User user;
     private Date dateTime;
     private Double totalAmount;
     private Double discount;
     private Double netAmount;
     private Set payLaterItems = new HashSet(0);
     private Set servicePaymentHistories = new HashSet(0);
     private Set serviceOrders = new HashSet(0);

    public ServiceInvoice() {
    }

	
    public ServiceInvoice(ServiceInvoiceStatus serviceInvoiceStatus, User user) {
        this.serviceInvoiceStatus = serviceInvoiceStatus;
        this.user = user;
    }
    public ServiceInvoice(ServiceInvoiceStatus serviceInvoiceStatus, User user, Date dateTime, Double totalAmount, Double discount, Double netAmount, Set payLaterItems, Set servicePaymentHistories, Set serviceOrders) {
       this.serviceInvoiceStatus = serviceInvoiceStatus;
       this.user = user;
       this.dateTime = dateTime;
       this.totalAmount = totalAmount;
       this.discount = discount;
       this.netAmount = netAmount;
       this.payLaterItems = payLaterItems;
       this.servicePaymentHistories = servicePaymentHistories;
       this.serviceOrders = serviceOrders;
    }
   
    public Integer getServiceInvoiceId() {
        return this.serviceInvoiceId;
    }
    
    public void setServiceInvoiceId(Integer serviceInvoiceId) {
        this.serviceInvoiceId = serviceInvoiceId;
    }
    public ServiceInvoiceStatus getServiceInvoiceStatus() {
        return this.serviceInvoiceStatus;
    }
    
    public void setServiceInvoiceStatus(ServiceInvoiceStatus serviceInvoiceStatus) {
        this.serviceInvoiceStatus = serviceInvoiceStatus;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getNetAmount() {
        return this.netAmount;
    }
    
    public void setNetAmount(Double netAmount) {
        this.netAmount = netAmount;
    }
    public Set getPayLaterItems() {
        return this.payLaterItems;
    }
    
    public void setPayLaterItems(Set payLaterItems) {
        this.payLaterItems = payLaterItems;
    }
    public Set getServicePaymentHistories() {
        return this.servicePaymentHistories;
    }
    
    public void setServicePaymentHistories(Set servicePaymentHistories) {
        this.servicePaymentHistories = servicePaymentHistories;
    }
    public Set getServiceOrders() {
        return this.serviceOrders;
    }
    
    public void setServiceOrders(Set serviceOrders) {
        this.serviceOrders = serviceOrders;
    }




}


