package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceDetails generated by hbm2java
 */
public class ServiceDetails  implements java.io.Serializable {


     private Integer serviceDetailsId;
     private Double costPerKm;
     private Double coverageArea;
     private Double minimumDistance;
     private Date lastUpdated;
     private Set serviceProviders = new HashSet(0);

    public ServiceDetails() {
    }

    public ServiceDetails(Double costPerKm, Double coverageArea, Double minimumDistance, Date lastUpdated, Set serviceProviders) {
       this.costPerKm = costPerKm;
       this.coverageArea = coverageArea;
       this.minimumDistance = minimumDistance;
       this.lastUpdated = lastUpdated;
       this.serviceProviders = serviceProviders;
    }
   
    public Integer getServiceDetailsId() {
        return this.serviceDetailsId;
    }
    
    public void setServiceDetailsId(Integer serviceDetailsId) {
        this.serviceDetailsId = serviceDetailsId;
    }
    public Double getCostPerKm() {
        return this.costPerKm;
    }
    
    public void setCostPerKm(Double costPerKm) {
        this.costPerKm = costPerKm;
    }
    public Double getCoverageArea() {
        return this.coverageArea;
    }
    
    public void setCoverageArea(Double coverageArea) {
        this.coverageArea = coverageArea;
    }
    public Double getMinimumDistance() {
        return this.minimumDistance;
    }
    
    public void setMinimumDistance(Double minimumDistance) {
        this.minimumDistance = minimumDistance;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
    public Set getServiceProviders() {
        return this.serviceProviders;
    }
    
    public void setServiceProviders(Set serviceProviders) {
        this.serviceProviders = serviceProviders;
    }




}


