package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private UserDetails userDetails;
     private LoginDetails loginDetails;
     private Set payLaterServices = new HashSet(0);
     private Set userLocationses = new HashSet(0);
     private Set serviceInvoices = new HashSet(0);

    public User() {
    }

	
    public User(UserDetails userDetails, LoginDetails loginDetails) {
        this.userDetails = userDetails;
        this.loginDetails = loginDetails;
    }
    public User(UserDetails userDetails, LoginDetails loginDetails, Set payLaterServices, Set userLocationses, Set serviceInvoices) {
       this.userDetails = userDetails;
       this.loginDetails = loginDetails;
       this.payLaterServices = payLaterServices;
       this.userLocationses = userLocationses;
       this.serviceInvoices = serviceInvoices;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public LoginDetails getLoginDetails() {
        return this.loginDetails;
    }
    
    public void setLoginDetails(LoginDetails loginDetails) {
        this.loginDetails = loginDetails;
    }
    public Set getPayLaterServices() {
        return this.payLaterServices;
    }
    
    public void setPayLaterServices(Set payLaterServices) {
        this.payLaterServices = payLaterServices;
    }
    public Set getUserLocationses() {
        return this.userLocationses;
    }
    
    public void setUserLocationses(Set userLocationses) {
        this.userLocationses = userLocationses;
    }
    public Set getServiceInvoices() {
        return this.serviceInvoices;
    }
    
    public void setServiceInvoices(Set serviceInvoices) {
        this.serviceInvoices = serviceInvoices;
    }




}


