package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0



/**
 * UserLocations generated by hbm2java
 */
public class UserLocations  implements java.io.Serializable {


     private Integer userLocationsId;
     private LocationType locationType;
     private User user;
     private Double longitute;
     private Double lattitude;

    public UserLocations() {
    }

	
    public UserLocations(LocationType locationType, User user) {
        this.locationType = locationType;
        this.user = user;
    }
    public UserLocations(LocationType locationType, User user, Double longitute, Double lattitude) {
       this.locationType = locationType;
       this.user = user;
       this.longitute = longitute;
       this.lattitude = lattitude;
    }
   
    public Integer getUserLocationsId() {
        return this.userLocationsId;
    }
    
    public void setUserLocationsId(Integer userLocationsId) {
        this.userLocationsId = userLocationsId;
    }
    public LocationType getLocationType() {
        return this.locationType;
    }
    
    public void setLocationType(LocationType locationType) {
        this.locationType = locationType;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getLongitute() {
        return this.longitute;
    }
    
    public void setLongitute(Double longitute) {
        this.longitute = longitute;
    }
    public Double getLattitude() {
        return this.lattitude;
    }
    
    public void setLattitude(Double lattitude) {
        this.lattitude = lattitude;
    }




}


