package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer userTypeId;
     private String userType;
     private Set userTypeHasUserPrivilleges = new HashSet(0);
     private Set loginDetailses = new HashSet(0);

    public UserType() {
    }

    public UserType(String userType, Set userTypeHasUserPrivilleges, Set loginDetailses) {
       this.userType = userType;
       this.userTypeHasUserPrivilleges = userTypeHasUserPrivilleges;
       this.loginDetailses = loginDetailses;
    }
   
    public Integer getUserTypeId() {
        return this.userTypeId;
    }
    
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set getUserTypeHasUserPrivilleges() {
        return this.userTypeHasUserPrivilleges;
    }
    
    public void setUserTypeHasUserPrivilleges(Set userTypeHasUserPrivilleges) {
        this.userTypeHasUserPrivilleges = userTypeHasUserPrivilleges;
    }
    public Set getLoginDetailses() {
        return this.loginDetailses;
    }
    
    public void setLoginDetailses(Set loginDetailses) {
        this.loginDetailses = loginDetailses;
    }




}


