package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0



/**
 * UserTypeHasUserPrivillege generated by hbm2java
 */
public class UserTypeHasUserPrivillege  implements java.io.Serializable {


     private Integer userTypeHasUserPrivillegeId;
     private UserPrivillege userPrivillege;
     private UserType userType;
     private Boolean allow;
     private String allowedPage;
     private String disallowedPage;

    public UserTypeHasUserPrivillege() {
    }

	
    public UserTypeHasUserPrivillege(UserPrivillege userPrivillege, UserType userType) {
        this.userPrivillege = userPrivillege;
        this.userType = userType;
    }
    public UserTypeHasUserPrivillege(UserPrivillege userPrivillege, UserType userType, Boolean allow, String allowedPage, String disallowedPage) {
       this.userPrivillege = userPrivillege;
       this.userType = userType;
       this.allow = allow;
       this.allowedPage = allowedPage;
       this.disallowedPage = disallowedPage;
    }
   
    public Integer getUserTypeHasUserPrivillegeId() {
        return this.userTypeHasUserPrivillegeId;
    }
    
    public void setUserTypeHasUserPrivillegeId(Integer userTypeHasUserPrivillegeId) {
        this.userTypeHasUserPrivillegeId = userTypeHasUserPrivillegeId;
    }
    public UserPrivillege getUserPrivillege() {
        return this.userPrivillege;
    }
    
    public void setUserPrivillege(UserPrivillege userPrivillege) {
        this.userPrivillege = userPrivillege;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public Boolean getAllow() {
        return this.allow;
    }
    
    public void setAllow(Boolean allow) {
        this.allow = allow;
    }
    public String getAllowedPage() {
        return this.allowedPage;
    }
    
    public void setAllowedPage(String allowedPage) {
        this.allowedPage = allowedPage;
    }
    public String getDisallowedPage() {
        return this.disallowedPage;
    }
    
    public void setDisallowedPage(String disallowedPage) {
        this.disallowedPage = disallowedPage;
    }




}


