package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * VehicleStatus generated by hbm2java
 */
public class VehicleStatus  implements java.io.Serializable {


     private Integer vehicleStatusId;
     private String vehicleStatus;
     private Set cabs = new HashSet(0);

    public VehicleStatus() {
    }

    public VehicleStatus(String vehicleStatus, Set cabs) {
       this.vehicleStatus = vehicleStatus;
       this.cabs = cabs;
    }
   
    public Integer getVehicleStatusId() {
        return this.vehicleStatusId;
    }
    
    public void setVehicleStatusId(Integer vehicleStatusId) {
        this.vehicleStatusId = vehicleStatusId;
    }
    public String getVehicleStatus() {
        return this.vehicleStatus;
    }
    
    public void setVehicleStatus(String vehicleStatus) {
        this.vehicleStatus = vehicleStatus;
    }
    public Set getCabs() {
        return this.cabs;
    }
    
    public void setCabs(Set cabs) {
        this.cabs = cabs;
    }




}


