package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * VehicleColour generated by hbm2java
 */
public class VehicleColour  implements java.io.Serializable {


     private Integer vehicleColourId;
     private String vehicleColour;
     private Set cabs = new HashSet(0);

    public VehicleColour() {
    }

    public VehicleColour(String vehicleColour, Set cabs) {
       this.vehicleColour = vehicleColour;
       this.cabs = cabs;
    }
   
    public Integer getVehicleColourId() {
        return this.vehicleColourId;
    }
    
    public void setVehicleColourId(Integer vehicleColourId) {
        this.vehicleColourId = vehicleColourId;
    }
    public String getVehicleColour() {
        return this.vehicleColour;
    }
    
    public void setVehicleColour(String vehicleColour) {
        this.vehicleColour = vehicleColour;
    }
    public Set getCabs() {
        return this.cabs;
    }
    
    public void setCabs(Set cabs) {
        this.cabs = cabs;
    }




}


