package Db;
// Generated Mar 9, 2015 10:30:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * VehicleModel generated by hbm2java
 */
public class VehicleModel  implements java.io.Serializable {


     private Integer vehicleModelId;
     private VehicleMake vehicleMake;
     private String vehicleModel;
     private Set cabs = new HashSet(0);

    public VehicleModel() {
    }

	
    public VehicleModel(VehicleMake vehicleMake) {
        this.vehicleMake = vehicleMake;
    }
    public VehicleModel(VehicleMake vehicleMake, String vehicleModel, Set cabs) {
       this.vehicleMake = vehicleMake;
       this.vehicleModel = vehicleModel;
       this.cabs = cabs;
    }
   
    public Integer getVehicleModelId() {
        return this.vehicleModelId;
    }
    
    public void setVehicleModelId(Integer vehicleModelId) {
        this.vehicleModelId = vehicleModelId;
    }
    public VehicleMake getVehicleMake() {
        return this.vehicleMake;
    }
    
    public void setVehicleMake(VehicleMake vehicleMake) {
        this.vehicleMake = vehicleMake;
    }
    public String getVehicleModel() {
        return this.vehicleModel;
    }
    
    public void setVehicleModel(String vehicleModel) {
        this.vehicleModel = vehicleModel;
    }
    public Set getCabs() {
        return this.cabs;
    }
    
    public void setCabs(Set cabs) {
        this.cabs = cabs;
    }




}


